// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Error = {};

var Register = {};

function Form(FieldValues) {
  return {};
}

var WatchValues = {};

export {
  $$Error ,
  Register ,
  Form ,
  WatchValues ,
  
}
/* No side effect */
