// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactHookForm from "./bindings/ReactHookForm.mjs";
import * as ReactHookForm$1 from "react-hook-form";

function ReForms$P(Props) {
  var children = Props.children;
  return React.createElement("p", {
              className: "mb-2"
            }, children);
}

var P = {
  make: ReForms$P
};

var FormTest = {};

function $$default(param) {
  ReactHookForm.Form(FormTest);
  var match = ReactHookForm$1.useForm({
        mode: "onSubmit"
      }, undefined);
  var register = match.register;
  var onSubmit = function (data, _event) {
    console.log(data.name.first);
    
  };
  console.log(match.formState.errors);
  var firstName = register("name.first");
  var category = register("category");
  var aboutYou = register("aboutYou");
  return React.createElement("div", undefined, React.createElement("form", {
                  onSubmit: match.handleSubmit(onSubmit)
                }, React.createElement("input", {
                      ref: firstName.ref,
                      name: firstName.name,
                      onBlur: firstName.onBlur,
                      onChange: firstName.onChange
                    }), React.createElement("input", {
                      ref: category.ref,
                      name: category.name,
                      onBlur: category.onBlur,
                      onChange: category.onChange
                    }), React.createElement("input", {
                      ref: aboutYou.ref,
                      name: aboutYou.name,
                      onBlur: aboutYou.onBlur,
                      onChange: aboutYou.onChange
                    }), React.createElement("input", {
                      type: "submit"
                    })));
}

export {
  P ,
  FormTest ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
